source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftLayout_Example' do
  pod "SwiftLayout", :path => "../"
end

target 'SwiftLayout-OSX' do
  pod "SwiftLayout", :path => "../"
end
